#!/bin/bash

FOLDER_PATH="/mnt/c/Users/shour/OneDrive - Livingston Public Schools/USACO/USACO/CPP";
FILE_PATH="$FOLDER_PATH/$1.cpp"

if [[ $FILE_PATH != *.cpp*]]; then
    FILE_PATH="$FILE_PATH.cpp"
fi

if [[ -e $FILE_PATH ]]; then
    echo FILE ALREADY EXISTS
else
#    cat $TO_ENTER > $FILE_PATH
#    touch $FILE_PATH
    touch "$FILE_PATH"
    echo -e $"#include <iostream>\n#include <cstdio>\n\nusing namespace std;\n\nint main() {\n\tfreopen(\"${2}.in\", \"r\", stdin);\n\tfreopen(\"${2}.out\", \"w\", stdout);\n\n}"  > "$FILE_PATH"
    vim "$FILE_PATH"
fi
