#!/bin/bash

FOLDER_PATH="/mnt/c/Users/shour/OneDrive - Livingston Public Schools/USACO/USACO/CPP/Book";

if [[ $1 == *".cpp" ]]; then 
    FILE_PATH="$FOLDER_PATH/$1"
else 
    FILE_PATH="$FOLDER_PATH/$1.cpp"
fi

if [[ -e $FILE_PATH ]]; then
    echo FILE ALREADY EXISTS
else
#    cat $TO_ENTER > $FILE_PATH
#    touch $FILE_PATH
    touch "$FILE_PATH"
    echo -e $"#include <bits/stdc++.h>\n\nusing namespace std;\n\nint main() {\n    ios::sync_with_stdio(false);\n    cin.tie(nullptr);\n\n}"  > "$FILE_PATH"
    nvim "$FILE_PATH"
fi
